"""add name to users

Revision ID: 1a8b5d0508cf
Revises: 530f1d675c5e
Create Date: 2025-03-22 13:37:33.232749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a8b5d0508cf'
down_revision: Union[str, None] = '530f1d675c5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('messages', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_column('users', 'name')
    op.alter_column('messages', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('chats', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
